In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris_data= load_iris()

In [5]:
x= iris_data.data
y= iris_data.target

In [6]:
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2)

In [7]:
x_train.shape

(120, 4)

In [8]:
x_test.shape

(30, 4)

In [9]:
from sklearn.naive_bayes import GaussianNB

In [10]:
model= GaussianNB()

In [11]:
model.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [12]:
y_pred= model.predict(x_test)

In [13]:
y_pred

array([2, 0, 1, 1, 2, 0, 0, 1, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 1, 1, 1,
       2, 0, 2, 2, 2, 2, 0, 0])

In [14]:
y_test

array([2, 0, 1, 1, 2, 0, 0, 1, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 1, 1, 2,
       2, 0, 1, 2, 2, 2, 0, 0])

In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [16]:
confusion_matrix(y_test, y_pred)

array([[ 9,  0,  0],
       [ 0,  7,  1],
       [ 0,  1, 12]], dtype=int64)

In [17]:
accuracy_score(y_test, y_pred)

0.9333333333333333

In [18]:
from sklearn.metrics import classification_report

In [19]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.88      0.88      0.88         8
           2       0.92      0.92      0.92        13

   micro avg       0.93      0.93      0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30



In [20]:
x[0]

array([5.1, 3.5, 1.4, 0.2])

In [21]:
new_point= np.array([5.2, 3.2, 1.5, 0.22])

In [22]:
class_index= model.predict(new_point.reshape(1, -1))

In [23]:
iris_data.target_names[class_index]

array(['setosa'], dtype='<U10')

## K-Nearest Neighbour Classifier

In [24]:
# Slow during training time
# Fast during testing

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
knn= KNeighborsClassifier(n_neighbors=3)

In [27]:
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [28]:
y_predicted= knn.predict(x_test)

In [29]:
print(classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.88      0.88      0.88         8
           2       0.92      0.92      0.92        13

   micro avg       0.93      0.93      0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30



In [30]:
accuracy_score(y_test, y_predicted)

0.9333333333333333

In [31]:
from sklearn.model_selection import GridSearchCV

In [32]:
knn1= KNeighborsClassifier()

In [33]:
params= {'n_neighbors': [3,5,7,9]}

In [34]:
grid= GridSearchCV(knn1, param_grid=params, cv=10)

In [35]:
grid.fit(x_train, y_train)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=10, error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_neighbors': [3, 5, 7, 9]}, pre_dispatch='2*n_jobs',
       refit=True, return_train_score='warn', scoring=None, verbose=0)

In [36]:
grid.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [38]:
knn_best= KNeighborsClassifier(n_neighbors=3)

In [39]:
knn_best.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [40]:
y_pred= knn_best.predict(x_test)

In [41]:
accuracy_score(y_test, y_pred)

0.9333333333333333

## Voting Classifier

In [43]:
from sklearn.ensemble import VotingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

In [44]:
nb= GaussianNB()
dtree= DecisionTreeClassifier()

In [50]:
ensemble_model= VotingClassifier(estimators=[('KNN', knn_best), ('DecisionTree', dtree),('NaiveBayes',nb)], weights=[0.3, 0.5, 0.2])

In [51]:
ensemble_model.fit(x_train, y_train)

VotingClassifier(estimators=[('KNN', KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')), ('DecisionTree', DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_fe...e=None,
            splitter='best')), ('NaiveBayes', GaussianNB(priors=None, var_smoothing=1e-09))],
         flatten_transform=None, n_jobs=None, voting='hard',
         weights=[0.3, 0.5, 0.2])

In [52]:
y_pred= ensemble_model.predict(x_test)

In [53]:
accuracy_score(y_test, y_pred)

0.9333333333333333